apiVersion: apps/v1 # version 설정
kind: Deployment # Deployment, Service, Job 등 지정
metadata:
  name: second-app-deployment # 이름 지정
spec: # 여기가 핵심. pod 사양을 설정
  replicas: 1 # 동일한 pod 개수 설정, 기본은 1, 0으로 설정해서 처음에 시작안하게 할 수도 있음.
  selector: # 관리할 pod를 매칭해줌.
    matchLabels:
      app: second-app
      tier: backend
  template: #pod에 대한 설정
    metadata: #pod에 대한 metadata
      labels: #key-value로 원하는 거 설정가능
        app: second-app
        tier: backend
    spec: # pod에 대한 spec
      containers:
        - name: second-node # 컨테이너 이름 지정
          image: liljoon/kub-first-app:2 # 이미지 지정
          imagePullPolicy: "Always"
        # - name: second-node # 이런 식으로 여러개 실행 가능.
        #   image:
